# Generated by Django 4.2.7 on 2023-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapi', '0002_alter_clientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
